quotes/quoteapp/urls.py
from django.urls import path

from . import seed, seed_mongo, views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('detail/<author_fullanme>', views.detail, name='detail'),
    path('find_quotes_by_tag/<tag>', views.find_quotes_by_tag, name='find_quotes_by_tag'),
    path('delete_all_quotes/', views.delete_all_quotes, name='delete_all_quotes'),
    path('delete_all_authors/', views.delete_all_authors, name='delete_all_authors'),
    path('delete_all_tags/', views.delete_all_tags, name='delete_all_tags'),
    path('seed_authors/', seed.seed_authors, name='seed_authors'),
    path('seed_quotes/', seed.seed_quotes, name='seed_quotes'),
    path('seed_authors_mongo/', seed_mongo.seed_authors, name='seed_authors_mongo'),
    path('seed_quotes_mongo/', seed_mongo.seed_quotes, name='seed_quotes_mongo'),

]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

quotes/quoteapp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Author(models.Model):
    fullname = models.CharField(max_length=25, null=False)
    born_date = models.DateField(null=True)
    born_location = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.fullname}"


class Quote(models.Model):
    # quote = models.CharField(max_length=300, null=False)
    quote = models.CharField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    # created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    # user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.quote}"

quotes/quoteapp/forms.py
from django.forms import (CharField, DateField, DateInput, ModelChoiceField,
                          ModelForm, Textarea, TextInput)

from .models import Author, Quote, Tag


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):

    quote = CharField(min_length=10, max_length=150, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all(), required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['quote', 'author']
        exclude = ['tags']


class AuthorForm(ModelForm):

    fullname = CharField(min_length=10, max_length=150, required=True, widget=TextInput())
    born_date = DateField(required=True, widget=DateInput(attrs={'type': 'date'}))
    born_location = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(required=True, widget=Textarea())


    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes/quoteapp/views.py
import collections

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import AuthorForm, QuoteForm, TagForm
from .models import Author, Quote, Tag


# Create your views here.
def top_ten_tags():
    tags = Tag.objects.all()

    counter_tags = collections.Counter()

    for tag in tags.iterator():
        coutes_with_tag = Quote.objects.filter(tags=tag.id).all()
        counter_tags[tag] = len(coutes_with_tag)

    # print(counter_tags.most_common(10))
    most_common_tags = [tag for tag in dict(counter_tags.most_common(10))]

    return most_common_tags


def main(request):
    all_quotes = Quote.objects.all()
    items_per_page = 10
    paginator = Paginator(all_quotes, items_per_page)
    page = request.GET.get('page')

    try:
        quotes = paginator.page(page)

    except PageNotAnInteger:
        quotes = paginator.page(1)

    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)

    most_common_tags = top_ten_tags()

    return render(
        request,
        "quoteapp/index.html",
        {"quotes": quotes, "most_common_tags": most_common_tags},
    )


def tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quoteapp:main")
        else:
            return render(request, "quoteapp/tag.html", {"form": form})

    return render(request, "quoteapp/tag.html", {"form": TagForm()})


def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            author = Author.objects.filter(id=request.POST["author"]).first()
            new_quote.author = author

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="quoteapp:main")
        else:
            return render(
                request,
                "quoteapp/quote.html",
                {"authors": authors, "tags": tags, "form": form},
            )

    return render(
        request,
        "quoteapp/quote.html",
        {"authors": authors, "tags": tags, "form": QuoteForm()},
    )


def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quoteapp:main")
        else:
            return render(request, "quoteapp/author.html", {"form": form})

    return render(request, "quoteapp/author.html", {"form": AuthorForm()})


def detail(request, author_fullanme):
    author = get_object_or_404(Author, fullname=author_fullanme)

    return render(request, "quoteapp/detail.html", {"author": author})


def delete_all_quotes(request):
    quotes = Quote.objects.all()
    for quote in quotes:
        quote.delete()

    return redirect(to="quoteapp:main")


def delete_all_authors(request):
    authors = Author.objects.all()
    for author in authors:
        author.delete()

    return redirect(to="quoteapp:main")


def delete_all_tags(request):
    tags = Tag.objects.all()
    for tag in tags:
        tag.delete()

    return redirect(to="quoteapp:main")


def find_quotes_by_tag(request, tag):
    tag = Tag.objects.filter(name=tag).first()
    # quotes = []
    # all_quotes = Quote.objects.all()

    # for quote in all_quotes.iterator():
    #     tags = [str(tag) for tag in quote.tags.iterator()]
    #     if tag.name in tags:
    #         quotes.append(quote)

    quotes = Quote.objects.filter(tags=tag.id).all()

    return render(request, "quoteapp/quotes.html", {"quotes": quotes, 'viewing_tag': tag})

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %} {% block content %}

<form method="POST" action="{% url 'quoteapp:author' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label> Author: {{ form.fullname }} </label>
    <span>{{ form.errors.fullname }}</span>
  </div>
  <div style="padding: 10px">
    <label> Born Date: {{ form.born_date }} </label>
    <span>{{ form.errors.born_date }}</span>
  </div>
  <div style="padding: 10px">
    <label> Born Location: {{ form.born_location }} </label>
    <span>{{ form.errors.born_location }}</span>
  </div>
  <!-- <div style="padding: 10px">
    <label> Description: {{ form.description }} </label>
    <span>{{ form.errors.description }}</span>
  </div> -->
  <div style="padding: 10px">
    <label for="description">Description: </label>
    <textarea id="description" name="description" rows="10" cols="50"> {{ form.description }} </textarea>
    <span>{{ form.errors.description }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="/static/style.css"/>
</head>

<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <ul>
                <li><a href="/" role="button">Quotes to Scrape</a></li>
            </ul>
        </nav>
        {% block content %}

        {% endblock %}
    </main>
</body>

</html>

quotes/quoteapp/templates/quoteapp/detail.html
{% extends "quoteapp/base.html" %} {% block content %}

<h1>{{author.fullname}}</h1>
<p><b>Born:</b> {{ author.born_date }}, {{ author.born_location }}</p>
<p><b>Description:</b></p>
<p>{{ author.description }}</p>
{% endblock %}

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Quote to Scrap</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"
    />
  </head>
  <body>
    {% load extract_tags %}
    <main
      class="container"
      style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px"
    >
      <nav
        style="
          margin-bottom: 20px;
          border-bottom: 2px solid;
          padding-left: 30px;
          padding-right: 30px;
        "
      >
        {% if user.is_authenticated %}
        <ul>
          <li>
            <a href="{% url 'quoteapp:quote' %}" role="button">Add Quote</a>
          </li>
          <li>
            <a href="{% url 'quoteapp:author' %}" role="button">Add Author</a>
          </li>
          <li><a href="{% url 'quoteapp:tag' %}" role="button">Add Tag</a></li>
        </ul>
        <ul>
          <li>Welcome <b>{{ user.username }}!</b></li>
          <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
          <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
          <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
          <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
      </nav>

      <nav>
        {% if user.is_authenticated %}
        <ul>
          <li>
            <a href="{% url 'quoteapp:delete_all_quotes' %}" role="button"
              >Delete all Quotes</a
            >
          </li>
          <li>
            <a href="{% url 'quoteapp:delete_all_authors' %}" role="button"
              >Delete all Authors</a
            >
          </li>
          <li>
            <a href="{% url 'quoteapp:delete_all_tags' %}" role="button"
              >Delete all Tags</a
            >
          </li>
          <li>
            <a href="{% url 'quoteapp:seed_quotes' %}" role="button"
              >Add test Quotes (JSON-file)</a
            >
          </li>
          <li>
            <a href="{% url 'quoteapp:seed_authors' %}" role="button"
              >Add test Authors (JSON-file)</a
            >
          </li>
          <li>
            <a href="{% url 'quoteapp:seed_quotes_mongo' %}" role="button"
              >Add test Quotes (MongoDB)</a
            >
          </li>
          <li>
            <a href="{% url 'quoteapp:seed_authors_mongo' %}" role="button"
              >Add test Authors (MongoDB)</a
            >
          </li>
        </ul>
        {% endif %}
      </nav>

      <div class="grid">
        <div style="width: 150%;">
          {% for quote in quotes %}
          <ul>
            <li>
              <p>{{ quote.quote }}</p>
              <p>
                by <b>{{quote.author}}</b>
                <a href="{% url 'quoteapp:detail' quote.author.fullname %}"
                  >(about)</a
                >
              </p>
              <p>
                Tags:
                <small>
                  {% for tag in quote.tags|tags %}
                  <a href="{% url 'quoteapp:find_quotes_by_tag' tag.name %}">
                    {{ tag.name }}</a
                  >, {% endfor %}
                </small>
              </p>
            </li>
          </ul>
          {% endfor %}
        </div>
        <div style="padding-left: 50%;">
          <h2>Top Ten Tags:</h2>
          <ul>
            {% for tag in most_common_tags %}
            <li>
              <a href="{% url 'quoteapp:find_quotes_by_tag' tag.name %}">
                {{ tag.name }}</a
              >
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </main>
    <nav class="container">
      <span class="step-links">

        {% if quotes.has_previous %}
        <a href="?page=1" role="button">&laquo; first</a>
        <a href="?page={{ quotes.previous_page_number }}" role="button">previous</a>
        {% endif %}

        <span class="current">
          Сторінка {{ quotes.number }} з {{ quotes.paginator.num_pages }}.
        </span>

        {% if quotes.has_next %}
            <a href="?page={{ quotes.next_page_number }}" role="button">next</a>
            <a href="?page={{ quotes.paginator.num_pages }}" role="button">last &raquo;</a>
        {% endif %}
      </span>
    </nav>
  </body>
</html>

quotes/quoteapp/templates/quoteapp/quote.html
{% extends "quoteapp/base.html" %} {% block content %}

<form method="POST" action="{% url 'quoteapp:quote' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label> Quote: {{ form.quote }} </label>
    <span>{{ form.errors.quote }}</span>
  </div>
  <div style="padding: 10px">
    <label>
      Select Author:
      <select name="author" required>
        {% for author in authors %}
        <option value="{{ author.id }}">{{ author.fullname }}</option>
        {% endfor %}
      </select>
    </label>
    <span>{{ form.errors.authors }}</span>
  </div>
  <div style="padding: 10px">
    <label>
      Select tags:
      <select name="tags" multiple="multiple" required>
        {% for tag in tags %}
        <option value="{{ tag.name }}">{{ tag.name }}</option>
        {% endfor %}
      </select>
    </label>
    <span>{{ form.errors.tags }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/quotes.html
{% extends "quoteapp/base.html" %} {% load extract_tags %}

{% block content %}
<h3>Viewing tag: <a href="{% url 'quoteapp:find_quotes_by_tag' viewing_tag.name %}"> {{ viewing_tag.name}}</a></h3>
{% for quote in quotes %}
<ul>
    <li>
        <p>{{ quote.quote }}</p>
        <p>
            by <b>{{quote.author}}</b>
            <a
            href="{% url 'quoteapp:detail' quote.author.fullname %}"
            >(about)</a
            >
      </p>
      <p>Tags:
        <small>
          {% for tag in quote.tags|tags %}
            <a href="{% url 'quoteapp:find_quotes_by_tag' tag.name %}"> {{ tag.name }}</a>,
          {% endfor %}
        </small></p>
    </li>
  </ul>
{% endfor %}
{% endblock %}

quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}